config/routes.rb
Rails.application.routes.draw do
  resources :terms

  root 'pages#home'

end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
    if params[:query].blank?
      @terms = Term.all
    else
      @terms = Term.find_by(:term => params[:query])
    end

    render json: @terms
  end

  def show
    @term = Term.find(params[:id])
  end

  def new
    @term = Term.new
  end

  def create
    @term = Term.new(secure_params)

    if @term.save
      redirect_to @term
    else
      render 'new'
    end
  end

  def edit
    @term = Term.find(params[:id])
  end

  def update
    @term = Term.find(params[:id])

    if @term.update(secure_params)
      redirect_to @term
    else
      render 'edit'
    end
  end

  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    redirect_to root_path
  end

  private

  def secure_params
    params.require(:term).permit(:term, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeveloperDictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Developer Dictionary</h1>

    <form>
      <div class="form-group">
       <input type="text" class="form-control" placeholder="Search for term" />
      </div>
    </form>

    <div class="result well"></div>

    <%= link_to 'Add new term', new_term_path %>
  </div>
</div>

app/views/terms/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Edit dictionary term</h1>
    <div class="form">
      <%= simple_form_for @term, html: { class: 'form-horizontal' } do |form| %>
        <%= form.error_notification %>
        <%= form.input :term, autofocus: true %>
        <%= form.input :description %>
        <%= form.button :submit, 'Submit', class: 'submit' %>
      <% end %>
    </div>
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/terms/index.html.erb
index

app/views/terms/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Add new dictionary term</h1>
    <div class="form">
      <%= simple_form_for @term, html: { class: 'form-horizontal' } do |form| %>
        <%= form.error_notification %>
        <%= form.input :term, autofocus: true %>
        <%= form.input :description %>
        <%= form.button :submit, 'Submit', class: 'submit' %>
      <% end %>
    </div>
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/terms/show.html.erb
<div class="jumbotron">
  <div class="container">
    <h1><%= @term.term %></h1>
    <p><%= @term.description %></p>
    <%= link_to 'Edit', edit_term_path %>
    <%= link_to 'Delete', term_path, method: :delete %>
    <%= link_to 'Back', root_path %>
  </div>
</div>